name: Top Ten
on: workflow_dispatch
    # schedule:
    #     - cron: "0 7 * * 1"
jobs:
    scrobbler:
        runs-on: windows-latest
        steps:
        - uses: actions/checkout@master
        - name: init proccess
          run: |
            $Year = Get-Date -UFormat %Y

            if (!(Test-Path -Path $Year)) {
                New-Item -Path $Year -ItemType Directory
            }

            pip install requests

            python lastFm\script.py --path "$Year" -t ${{ secrets.TOKEN_LASTFM }}

            git add "$Year"
        - name: Commit & Push changes
          uses: actions-js/push@master
          with:
            github_token: ${{ secrets.TOKEN }}
            author_name: EdgarVaguencia
            author_email: ${{ secrets.EMAIL }}
            message: 'Recomendación musical :headphones:'
